#!/usr/bin/env node
/**
 * PALETTE GENERATOR — writes the v2 color primitives as open-format token files.
 * ════════════════════════════════════════════════════════════════════
 * Reads ./inputs.json (the agreed colors + the rules for new steps) and writes:
 *
 *   tokens/base/gray.json      gray 50–950, white, black   (same in both modes)
 *   tokens/{light,dark}/hues.json      each hue 50–950, mode offset applied
 *   tokens/{light,dark}/gradient.json  the nine stops + the spectrum gradient
 *   tokens/{light,dark}/shadows.json   the level ladder, cast in a gray step
 *
 * The output files are the source of truth; this script is the tool that
 * writes them. Retune = edit inputs.json, regenerate, review the diff.
 * Never edit the generated files by hand — `--check` fails if they differ.
 *
 *   node tools/palette/generate.mjs           write the files
 *   node tools/palette/generate.mjs --check   exit 1 if the files are stale
 *   node tools/palette/generate.mjs --report  print every step's L / C / H
 *
 * Pinned steps are agreed values: copied, never recomputed (status `working`).
 * New steps are provisional (status `exploring`) until tuned and display-checked.
 * The color maths matches src/pages/rounds/_working.ts exactly, so a pinned
 * color renders byte-for-byte as it does on the working pages today.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');
const OUT = join(ROOT, 'tokens');
const IN = JSON.parse(readFileSync(join(HERE, 'inputs.json'), 'utf8'));

const SERIES = ['50', '100', '200', '300', '400', '500', '600', '700', '800', '900', '950'];
const MODES = ['light', 'dark'];
const HUES = Object.keys(IN.hues);
const NOTE = 'Generated by tools/palette/generate.mjs from tools/palette/inputs.json. Do not edit by hand: change the inputs and regenerate.';

/* ── OKLCH ⇄ sRGB — identical to src/pages/rounds/_working.ts ─────── */
const lin = c => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
const gam = c => (c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055);

/** hex → [L 0–100, C, H°] */
function hexToOklch(hex) {
  const n = parseInt(hex.replace('#', ''), 16);
  const [r, g, b] = [(n >> 16) & 255, (n >> 8) & 255, n & 255].map(v => lin(v / 255));
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  const L = 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s;
  const A = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s;
  const B = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s;
  return [L * 100, Math.hypot(A, B), ((Math.atan2(B, A) * 180) / Math.PI + 360) % 360];
}
function oklchToRgb(L, C, H) {
  const h = (H * Math.PI) / 180, Lf = L / 100, A = C * Math.cos(h), B = C * Math.sin(h);
  const l = (Lf + 0.3963377774 * A + 0.2158037573 * B) ** 3;
  const m = (Lf - 0.1055613458 * A - 0.0638541728 * B) ** 3;
  const s = (Lf - 0.0894841775 * A - 1.291485548 * B) ** 3;
  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];
}
const inGamut = rgb => rgb.every(c => c >= -1e-4 && c <= 1 + 1e-4);
/** Gamut-map by reducing chroma, holding lightness and hue. Returns [hex, clipped]. */
function oklchToHexInfo(L, C, H) {
  let rgb = oklchToRgb(L, C, H), clipped = false;
  if (!inGamut(rgb)) {
    clipped = true;
    let lo = 0, hi = C;
    for (let i = 0; i < 30; i++) { const mid = (lo + hi) / 2; if (inGamut(oklchToRgb(L, mid, H))) lo = mid; else hi = mid; }
    rgb = oklchToRgb(L, lo, H);
  }
  const hex = '#' + rgb.map(c => Math.round(Math.min(Math.max(gam(Math.min(Math.max(c, 0), 1)), 0), 1) * 255).toString(16).padStart(2, '0')).join('');
  return [hex, clipped];
}
const oklchToHex = (L, C, H) => oklchToHexInfo(L, C, H)[0];
const saturate = (hex, s) => { const [L, C, H] = hexToOklch(hex); return oklchToHexInfo(L, C * s, H); };
const lerp = (a, b, t) => a + (b - a) * t;
const lerpH = (a, b, t) => { const d = ((b - a + 540) % 360) - 180; return (a + d * t + 360) % 360; };

/* ── Steps ────────────────────────────────────────────────────────── */
/** One step as a record: hex plus where it came from. */
const step = (hex, ext) => ({ hex, ...ext });

function gray11() {
  const pin = IN.gray.pinned, out = {};
  const [L1, C1, H1] = hexToOklch(pin['200'].hex), [L2, C2, H2] = hexToOklch(pin['600'].hex);
  for (const s of SERIES) {
    if (pin[s]) { out[s] = step(pin[s].hex, { pinned: true, was: pin[s].was }); continue; }
    const t = IN.gray.new[s].t;
    const [hex, clipped] = oklchToHexInfo(lerp(L1, L2, t), lerp(C1, C2, t), lerpH(H1, H2, t));
    out[s] = step(hex, { pinned: false, rule: `${IN.gray.new._rule}, t = ${t}`, clipped });
  }
  return out;
}

/** A hue's 11 steps before the mode offset. */
function hueBase(h) {
  const pin = IN.hues[h].pinned, R = IN.hue_new, out = {};
  for (const [s, v] of Object.entries(pin)) out[s] = step(v.hex, { pinned: true, was: v.was });
  const ok = s => hexToOklch(pin[s].hex);
  for (const s of ['50', '900', '950']) {
    const r = R[s], [, C, H] = ok(r.C_from);
    const [hex, clipped] = oklchToHexInfo(r.L, C * r.C_factor, H);
    out[s] = step(hex, { pinned: false, rule: r._rule, clipped });
  }
  {
    const [a, b] = R['400'].between, [La, Ca, Ha] = ok(a), [Lb, Cb, Hb] = ok(b);
    const [hex, clipped] = oklchToHexInfo((La + Lb) / 2, lerp(Ca, Cb, 0.5), lerpH(Ha, Hb, 0.5));
    out['400'] = step(hex, { pinned: false, rule: R['400']._rule, clipped });
  }
  return out;
}

/** A hue's 11 steps for a mode: the offset applied to every step, as the working ramp does. */
function hue11(h, mode) {
  const b = hueBase(h), out = {};
  for (const s of SERIES) {
    const [hex, clipped] = saturate(b[s].hex, IN.saturation[mode]);
    out[s] = { ...b[s], hex, clipped: Boolean(b[s].clipped || clipped), base: b[s].hex };
  }
  return out;
}

/* ── Token objects (DTCG 2025.10) ─────────────────────────────────── */
const r4 = x => Math.round(x * 1e4) / 1e4;
const r2 = x => Math.round(x * 1e2) / 1e2;
function colorValue(hex) {
  const [L, C, H] = hexToOklch(hex);
  return { colorSpace: 'oklch', components: [r4(L / 100), r4(C), r2(H)], hex };
}
function colorToken(st, extra = {}) {
  const meta = { status: st.pinned ? 'working' : 'exploring', generated: true, pinned: Boolean(st.pinned) };
  if (st.was) meta.was = st.was;
  if (st.rule) meta.rule = st.rule;
  if (st.clipped) meta.gamutMapped = true;
  return { $value: colorValue(st.hex), ...extra, $extensions: { 'org.openmined': meta } };
}

function grayFile() {
  const g = gray11();
  const fixed = hex => ({ $value: colorValue(hex), $extensions: { 'org.openmined': { status: 'working', generated: true, pinned: true } } });
  return {
    $description: `Gray, 50–950, plus white and black outside the scale. Neutrals take no mode offset. ${NOTE}`,
    gray: { $type: 'color', ...Object.fromEntries(SERIES.map(s => [s, colorToken(g[s])])) },
    white: { $type: 'color', ...fixed(IN.white) },
    black: { $type: 'color', ...fixed(IN.black) },
  };
}

function huesFile(mode) {
  return {
    $description: `Hue primitives, 50–950, ${mode} mode: chroma × ${IN.saturation[mode]} on every step. The key (500) is the agreed Ink key. ${NOTE}`,
    ...Object.fromEntries(HUES.map(h => {
      const r = hue11(h, mode);
      return [h, { $type: 'color', ...Object.fromEntries(SERIES.map(s => [s, colorToken(r[s])])) }];
    })),
  };
}

function gradientFile(mode) {
  const stops = IN.gradient.stops, n = stops.length;
  const tokens = {}, value = [];
  stops.forEach((st, i) => {
    const position = r4(i / (n - 1));
    if (st.ref) {
      tokens[st.name] = { $value: `{${st.ref}.key}`, $description: `Family stop: the ${st.ref} key.`, $extensions: { 'org.openmined': { status: 'working', generated: true } } };
    } else {
      const [hex, clipped] = saturate(st.hex, IN.saturation[mode]);
      tokens[st.name] = colorToken({ hex, pinned: true, was: `fitted stop ${st.hex} × ${IN.saturation[mode]}`, clipped }, { $description: 'Fitted stop: no hue family; fitted to the palette.' });
    }
    value.push({ color: `{gradient.${st.name}}`, position });
  });
  return {
    $description: `The brand gradient, ${mode} mode: nine stops, family stops are hue keys. ${NOTE}`,
    gradient: {
      $type: 'color',
      ...tokens,
      spectrum: { $type: 'gradient', $value: value, $description: 'The full brand arc, gold → yellow.', $extensions: { 'org.openmined': { status: 'working', generated: true } } },
    },
  };
}

/** Shadows: generated so the ink is always a gray step's own value, never a typed color. */
function shadowsFile(mode) {
  const S = IN.shadows, inkName = S.ink[mode];
  const inkHex = inkName === 'black' ? IN.black : inkName === 'white' ? IN.white : gray11()[inkName.split('.')[1]].hex;
  const px = value => ({ value, unit: 'px' });
  const layer = (l, inset) => {
    const [x, y, blur, spread] = l.geometry;
    return { color: { ...colorValue(inkHex), alpha: l.alpha[mode] }, offsetX: px(x), offsetY: px(y), blur: px(blur), spread: px(spread), ...(inset ? { inset: true } : {}) };
  };
  return {
    $description: `Shadows, ${mode} mode: one rung per surface level (base casts nothing), cast in {${inkName}}. ${NOTE}`,
    shadow: {
      $type: 'shadow',
      ...Object.fromEntries(Object.entries(S.levels).map(([lvl, v]) => {
        const layers = v.layers.map(l => layer(l, v.inset));
        return [lvl, { $value: layers.length === 1 ? layers[0] : layers, $extensions: { 'org.openmined': { status: 'working', generated: true, ink: `{${inkName}}` } } }];
      })),
    },
  };
}

/* ── Run ──────────────────────────────────────────────────────────── */
const files = {
  'base/gray.json': grayFile(),
  ...Object.fromEntries(MODES.flatMap(m => [[`${m}/hues.json`, huesFile(m)], [`${m}/gradient.json`, gradientFile(m)], [`${m}/shadows.json`, shadowsFile(m)]])),
};
const text = obj => JSON.stringify(obj, null, 2) + '\n';
const args = new Set(process.argv.slice(2));

if (args.has('--report')) {
  const row = (name, st) => {
    const [L, C, H] = hexToOklch(st.hex);
    return `${name.padEnd(12)} ${st.hex}  L ${L.toFixed(1).padStart(5)}  C ${C.toFixed(3)}  H ${H.toFixed(0).padStart(3)}  ${st.pinned ? 'agreed' : 'NEW   '}${st.clipped ? '  gamut-mapped' : ''}`;
  };
  const g = gray11();
  console.log('GRAY'); for (const s of SERIES) console.log(row(`gray ${s}`, g[s]));
  for (const m of MODES) for (const h of HUES) {
    console.log(`\n${h.toUpperCase()} — ${m}`); const r = hue11(h, m);
    for (const s of SERIES) console.log(row(`${h} ${s}`, r[s]));
  }
} else if (args.has('--check')) {
  let stale = [];
  for (const [p, obj] of Object.entries(files)) {
    let cur = null; try { cur = readFileSync(join(OUT, p), 'utf8'); } catch {}
    if (cur !== text(obj)) stale.push(p);
  }
  if (stale.length) { console.error(`Stale or hand-edited: ${stale.join(', ')}. Run node tools/palette/generate.mjs`); process.exit(1); }
  console.log('Palette tokens are up to date.');
} else {
  for (const [p, obj] of Object.entries(files)) {
    mkdirSync(dirname(join(OUT, p)), { recursive: true });
    writeFileSync(join(OUT, p), text(obj));
    console.log(`wrote tokens/${p}`);
  }
}
