#!/usr/bin/env node
/**
 * TOKEN BUILD — turns tokens/ (Design Tokens 2025.10) into the v2 outputs.
 * ════════════════════════════════════════════════════════════════════
 * Reads tokens/resolver.json, resolves each mode, and writes:
 *
 *   src/tokens/v2/tokens.css          CSS custom properties, every context
 *   src/tokens/v2/brand-colors.js     the JS-side colors for canvas / WebGL
 *   src/tokens/v2/tokens.light.json   flat resolved values + status, per mode
 *   src/tokens/v2/tokens.dark.json
 *
 *   node tools/tokens/build.mjs           validate, then write the outputs
 *   node tools/tokens/build.mjs --check   validate, and exit 1 if any output
 *                                         is stale or was edited by hand
 *
 * Validation: every file in tokens/ against the official schemas (vendored in
 * ./schemas), then every reference must resolve with no cycles.
 *
 * CSS shape — the same mechanism as v1's tokens.css:
 *   :root                                        light
 *   [data-theme="dark"]                          dark (set by the theme script)
 *   [data-section="always-dark"]                 dark, whatever the page
 *   [data-section="always-light"]                light, whatever the page
 *   [data-section="invert"]                      the opposite of the page
 * Every block declares the full set: a custom property's var() is substituted
 * where it is declared, so a section must redeclare the aliases, not just the
 * primitives, for them to pick up its mode.
 * Primitives are written as hex (exactly what was reviewed); aliases as
 * var(--target), so the chain stays visible and overridable.
 *
 * No dependencies beyond the schema validator (ajv). The token files use no
 * custom syntax, so any 2025.10 tool (e.g. Terrazzo) can read them too.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import Ajv from 'ajv';
import addFormats from 'ajv-formats';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');
const SRC = join(ROOT, 'tokens');
const OUT = join(ROOT, 'src', 'tokens', 'v2');
const SCHEMAS = join(HERE, 'schemas', '2025.10');
const SCHEMA_BASE = 'https://www.designtokens.org/schemas/2025.10/';
const HEADER = 'OpenMined v2 tokens. Generated by tools/tokens/build.mjs from tokens/ — do not edit by hand.';

const readJson = p => JSON.parse(readFileSync(p, 'utf8'));
const walkFiles = d => readdirSync(d).flatMap(f => (statSync(join(d, f)).isDirectory() ? walkFiles(join(d, f)) : [join(d, f)]));
const fail = msg => { console.error(`✖ ${msg}`); process.exit(1); };

/* ── 1. Schema validation ─────────────────────────────────────────── */
function validate() {
  const ajv = new Ajv({ strict: false, allErrors: true });
  addFormats(ajv);
  for (const f of walkFiles(SCHEMAS).filter(f => f.endsWith('.json'))) {
    const s = readJson(f);
    ajv.addSchema(s, s.$id || SCHEMA_BASE + relative(SCHEMAS, f));
  }
  const format = ajv.getSchema(SCHEMA_BASE + 'format.json');
  const resolver = ajv.getSchema(SCHEMA_BASE + 'resolver.json');
  const errors = [];
  for (const f of walkFiles(SRC).filter(f => f.endsWith('.json'))) {
    const v = f.endsWith('resolver.json') ? resolver : format;
    if (!v(readJson(f))) errors.push(`${relative(ROOT, f)}: ${v.errors.slice(0, 3).map(e => `${e.instancePath || '/'} ${e.message}`).join('; ')}`);
  }
  if (errors.length) fail(`schema validation failed:\n  ${errors.join('\n  ')}`);
}

/* ── 2. Resolve a mode ────────────────────────────────────────────── */
const isToken = v => v && typeof v === 'object' && '$value' in v;

/** Deep-merge token documents; later sources win, token by token. */
function merge(into, from) {
  for (const [k, v] of Object.entries(from)) {
    if (k === '$description' && into !== from) continue;
    if (v && typeof v === 'object' && !Array.isArray(v) && !isToken(v) && into[k] && typeof into[k] === 'object') merge(into[k], v);
    else into[k] = v;
  }
  return into;
}

/** Merge the sources the resolver names for one context of each modifier. */
function documentFor(mode) {
  const R = readJson(join(SRC, 'resolver.json'));
  const doc = {};
  const add = src => {
    if (src.$ref?.startsWith('#/sets/')) return R.sets[src.$ref.slice(7)].sources.forEach(add);
    if (src.$ref) return merge(doc, readJson(join(SRC, src.$ref)));
    merge(doc, src); // inline tokens
  };
  for (const step of R.resolutionOrder) {
    const ref = step.$ref ?? '';
    if (ref.startsWith('#/sets/')) R.sets[ref.slice(7)].sources.forEach(add);
    else if (ref.startsWith('#/modifiers/')) {
      const m = R.modifiers[ref.slice(12)];
      const ctx = m.contexts[mode] ?? m.contexts[m.default];
      if (!ctx) fail(`resolver: no context "${mode}"`);
      ctx.forEach(add);
    }
  }
  return doc;
}

/** Flatten to path → { type, value, ext }. Group $type is inherited; $root takes the group's path. */
function flatten(doc) {
  const out = {};
  (function walk(node, path, type) {
    for (const [k, v] of Object.entries(node)) {
      if (k.startsWith('$') && k !== '$root') continue;
      if (!v || typeof v !== 'object') continue;
      const p = k === '$root' ? path : [...path, k];
      const t = v.$type ?? type;
      if (isToken(v)) out[p.join('.')] = { type: t, value: v.$value, ext: v.$extensions?.['org.openmined'] ?? {} };
      else walk(v, p, t);
    }
  })(doc, [], undefined);
  return out;
}

const REF = /^\{([^{}]+)\}$/;
const refPath = s => s.match(REF)[1].replace(/\.\$root$/, '');

/** Fully resolve a value: references followed, composites walked. Throws on missing or circular refs. */
function resolveValue(flat, value, chain = []) {
  if (typeof value === 'string' && REF.test(value)) {
    const p = refPath(value);
    if (chain.includes(p)) throw new Error(`circular reference: ${[...chain, p].join(' → ')}`);
    if (!flat[p]) throw new Error(`unresolved reference ${value}${chain.length ? ` (in ${chain[0]})` : ''}`);
    return resolveValue(flat, flat[p].value, [...chain, p]);
  }
  if (Array.isArray(value)) return value.map(v => resolveValue(flat, v, chain));
  if (value && typeof value === 'object' && !('colorSpace' in value)) {
    if ('$ref' in value) throw new Error(`JSON Pointer references are not supported by this build (${value.$ref})`);
    return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, resolveValue(flat, v, chain)]));
  }
  return value;
}

function resolveMode(mode) {
  const flat = flatten(documentFor(mode));
  const tokens = {};
  for (const [p, t] of Object.entries(flat)) {
    let resolved;
    try { resolved = resolveValue(flat, t.value, [p]); } catch (e) { fail(`${mode}: ${p}: ${e.message}`); }
    tokens[p] = { ...t, resolved, alias: typeof t.value === 'string' && REF.test(t.value) ? refPath(t.value) : null };
  }
  return tokens;
}

/* ── 3. Formatting ────────────────────────────────────────────────── */
const cssName = p => '--' + p.replace(/\./g, '-');
const dim = d => (d.value === 0 ? '0' : `${d.value}${d.unit}`);
const rgbAlpha = c => `rgb(${[1, 3, 5].map(i => parseInt(c.hex.slice(i, i + 2), 16)).join(' ')} / ${c.alpha})`;
const colorCss = c => (c.alpha !== undefined && c.alpha !== 1 ? rgbAlpha(c) : c.hex);

/** A value as CSS. `raw` is the source value: gradient stops that were references stay var(), unless `literal`. */
function cssValue(t, raw, literal = false) {
  switch (t.type) {
    case 'color': return colorCss(t.resolved);
    case 'dimension': return dim(t.resolved);
    case 'shadow': {
      const layers = Array.isArray(t.resolved) ? t.resolved : [t.resolved];
      return layers.map(s => `${s.inset ? 'inset ' : ''}${dim(s.offsetX)} ${dim(s.offsetY)} ${dim(s.blur)} ${dim(s.spread)} ${colorCss(s.color)}`).join(', ');
    }
    case 'gradient': {
      const stops = raw.map((s, i) => {
        const color = !literal && typeof s.color === 'string' && REF.test(s.color) ? `var(${cssName(refPath(s.color))})` : colorCss(t.resolved[i].color);
        return `${color} ${+(t.resolved[i].position * 100).toFixed(2)}%`;
      });
      return `linear-gradient(90deg, ${stops.join(', ')})`;
    }
    default: return JSON.stringify(t.resolved);
  }
}

function declarations(tokens) {
  return Object.entries(tokens).map(([p, t]) => {
    const value = t.alias ? `var(${cssName(t.alias)})` : cssValue(t, t.value);
    return `  ${cssName(p)}: ${value};`;
  }).join('\n');
}

function buildCss(modes) {
  const block = (selector, mode) => `${selector} {\n  color-scheme: ${mode};\n${declarations(modes[mode])}\n}`;
  return [
    `/* ${HEADER}\n   Light on :root, dark on [data-theme="dark"]; data-section contexts get the full set.\n   Status lives in tokens/ ($extensions) and in tokens.{light,dark}.json. */`,
    // Order and specificity do the work: the dark block comes later, so it wins ties;
    // `[data-theme="dark"] [data-section="invert"]` (0,2,0) beats `[data-section="invert"]`
    // (0,1,0), so invert is always the opposite of the page — as in v1 — at any nesting depth.
    block(':root,\n[data-section="always-light"],\n[data-theme="dark"] [data-section="invert"]', 'light'),
    block('[data-theme="dark"],\n[data-section="always-dark"],\n[data-section="invert"]', 'dark'),
  ].join('\n\n') + '\n';
}

function buildJson(tokens) {
  const out = { $description: HEADER };
  for (const [p, t] of Object.entries(tokens)) {
    out[cssName(p)] = { value: t.alias ? `var(${cssName(t.alias)})` : cssValue(t, t.value), resolved: cssValue(t, t.value, true), type: t.type, ...(t.ext.status ? { status: t.ext.status } : {}) };
  }
  return JSON.stringify(out, null, 2) + '\n';
}

function buildJs(modes) {
  const colors = m => Object.fromEntries(Object.entries(modes[m]).filter(([, t]) => t.type === 'color').map(([p, t]) => [p.replace(/\./g, '-'), colorCss(t.resolved)]));
  // Every gradient token (the spectrum and each graphic's list), as its stops' colors.
  const lists = m => Object.fromEntries(Object.entries(modes[m]).filter(([p, t]) => t.type === 'gradient')
    .map(([p, t]) => [p.replace(/^gradient\./, ''), t.resolved.map(s => colorCss(s.color))]));
  return `/**
 * ${HEADER}
 * The JS-side colors for canvas / WebGL embeds, which can't read CSS variables.
 * Names match the CSS custom properties without the leading "--".
 */
export const COLORS = ${JSON.stringify({ light: colors('light'), dark: colors('dark') }, null, 2)};

/** Each gradient's stops, in order, per mode: the spectrum and each graphic's own list. */
export const GRADIENTS = ${JSON.stringify({ light: lists('light'), dark: lists('dark') }, null, 2)};
`;
}

/* ── 4. Run ───────────────────────────────────────────────────────── */
validate();
const modes = { light: resolveMode('light'), dark: resolveMode('dark') };
const keys = m => Object.keys(modes[m]).sort().join();
if (keys('light') !== keys('dark')) fail('light and dark define different token names');

const outputs = {
  'tokens.css': buildCss(modes),
  'brand-colors.js': buildJs(modes),
  'tokens.light.json': buildJson(modes.light),
  'tokens.dark.json': buildJson(modes.dark),
};

if (process.argv.includes('--check')) {
  const stale = Object.entries(outputs).filter(([f, text]) => { try { return readFileSync(join(OUT, f), 'utf8') !== text; } catch { return true; } }).map(([f]) => f);
  if (stale.length) fail(`stale or hand-edited: ${stale.map(f => `src/tokens/v2/${f}`).join(', ')}. Run npm run tokens`);
  console.log(`✓ tokens valid; ${Object.keys(modes.light).length} per mode; outputs up to date`);
} else {
  mkdirSync(OUT, { recursive: true });
  for (const [f, text] of Object.entries(outputs)) writeFileSync(join(OUT, f), text);
  console.log(`✓ tokens valid; ${Object.keys(modes.light).length} per mode; wrote ${Object.keys(outputs).map(f => `src/tokens/v2/${f}`).join(', ')}`);
}
